### ISSUE TITLE
弹幕无法所有网站正确显示，即使正确填写Media Query

### ISSUE THREAD

**Issue by Tourist-ChenHao** [Mr-Quin/danmaku-anywhere#13]
问题：经测试发现，目前只有B站能正确挂载弹幕，其他网站均无法正常显示弹幕。

排查：1. 通过调试工具查询，无法正常显示弹幕的网站，div节点为“.danmaku-anywhere”下的，div子节点“#danmaku-anywhere-danmaku-container”并没有进行DOM渲染；另外加载的弹幕文件数量不为0
2. 猜测原因可能是程序无法获取到当前视频进度，导致无法正确加载弹幕

希望作者早日修复。

**Comment by Tourist-ChenHao** [comment]
补上测试网站：
腾讯视频(v.qq.com)，爱奇艺(iqiyi.com)，芒果视频(mgtv.com)，樱花动漫(dmla5.com)

**Comment by Mr-Quin** [comment]
## 芒果视频
测试可用
https://w.mgtv.com/b/634552/20768897.html?fpa=33341&fpos=1&lastp=ch_home
![image](https://github.com/Mr-Quin/danmaku-anywhere/assets/8700123/ee53b460-16a4-41fc-bfa0-32ae5529a30a)

## 腾讯视频
测试可用
https://v.qq.com/x/cover/mzc002002eyu6c2/h0048di7p5x.html
![image](https://github.com/Mr-Quin/danmaku-anywhere/assets/8700123/6ed1fa85-3128-4a59-98c2-361c222746c6)
`#player > div.txp_videos_container > video:nth-child(1)`

## 爱奇艺
测试可用
https://www.iqiyi.com/v_uusysnhgww.html?bkt=bucket_base&e=71043f60-1bb1-4869-a4d4-169088bd0f81&stype=2&c1=%E6%B8%B8%E6%88%8F&vfrm=category_lib.8&vfrmblk=S:lib_1_video&vfrmrst=S:lib_1_video_image1
![image](https://github.com/Mr-Quin/danmaku-anywhere/assets/8700123/ebe0628b-9fdd-4483-a237-0e8aed4e18d3)
`#flashbox > iqpdiv > iqpdiv.iqp-player > iqpdiv.iqp-player-videolayer > iqpdiv > video`

以上网站我都没有账号，只能测试一下免费视频。不同的视频可能有不同的包装方法，不保证通用。大概率只是需要更细致的media query

樱花动漫我加载不出来不清楚，但是看了一下他们用了iframe, iframe的情况url pattern要填iframe的src

**Comment by Mr-Quin** [comment]
如果有可以复现的，无法正确显示的视频可以给个地址和配置

**Comment by Mr-Quin** [comment]
还是存在一些问题的，已知
有些media query明明是正确的但是无法获取节点 #14
url pattern含有`*`会匹配失败 #15 
这两个问题都可以通过config绕过，不应该导致弹幕失效

**Comment by Mr-Quin** [comment]
樱花动漫我也试成功了

樱花动漫的视频播放器在iframe内，iframe的情况复杂一点，需要在url patterns里加入iframe的src,我播放的视频为`https://danmu.yhdmjx.com/*`

此时插件的控件会注入在iframe内

![image](https://github.com/Mr-Quin/danmaku-anywhere/assets/8700123/713eba03-a498-44f7-bb41-94ca1ea20331)
![image](https://github.com/Mr-Quin/danmaku-anywhere/assets/8700123/83cd8876-f2f4-4a7a-9ea7-43be12749f3b)

目前没有针对iframe做适配，体验不会很好

**Comment by Tourist-ChenHao** [comment]
很高兴能收到你的回复，根据你的方式进行复现，现在已经可以挂载弹幕了。我必须承认，之前因为Config的配置错误导致无法显示。
错误原因：
1. URL [Patterns处，采用*.website/*格式，按道理是可以匹配的.[15](https://github.com/Mr-Quin/danmaku-anywhere/issues/15)
2. Media Query处，格式没有详细填写，而是简单采用#id > video，主要原因是主页的Readme没有具体举例说明导致
---
另外现在出现第二个问题，当网站可以正确挂载弹幕，而一旦打开视频全屏弹幕会失效。通过网页调试工具排查，全屏时，弹幕DOM元素处于正常渲染中，且z-index权重为999999

**以下为视频网站截图**
> 案例网站的网站和Config 均与上面comment信息保持一致。故不重复举例

`芒果TV`
<img width="800" alt="iShot_2024-04-07_15 50 01" src="https://github.com/Mr-Quin/danmaku-anywhere/assets/26212364/e2bbbbff-9f23-4524-b93b-d100f5151474">
_正常窗口_
<img width="800" alt="iShot_2024-04-07_15 50 10" src="https://github.com/Mr-Quin/danmaku-anywhere/assets/26212364/74aafbf5-c998-405b-81ff-8314c93a69aa">
_视频全屏_
---
`腾讯视频`
<img width="800" alt="iShot_2024-04-07_15 53 07" src="https://github.com/Mr-Quin/danmaku-anywhere/assets/26212364/96ac39e8-cc82-4621-9adf-bf5ef0942b2e">
_正常窗口_
<img width="800" alt="iShot_2024-04-07_15 53 19" src="https://github.com/Mr-Quin/danmaku-anywhere/assets/26212364/12290a33-191d-4989-ad76-dac36bd203a6">
_视频全屏_
---
`樱花动漫`
<img width="800" alt="iShot_2024-04-07_15 54 47" src="https://github.com/Mr-Quin/danmaku-anywhere/assets/26212364/da3284b2-44c8-432b-930a-21521c2ace8f">
_正常窗口_
<img width="800" alt="iShot_2024-04-07_15 55 39" src="https://github.com/Mr-Quin/danmaku-anywhere/assets/26212364/807199a4-a5d0-4557-a1f5-aef2bdf60607">
_视频全屏_

**Comment by Mr-Quin** [comment]
全屏不显示的问题确实存在，开了一个新bug #18 
media query和url pattern的问题应该在`v0.9.0`中修复了，你可以试一下
