### ISSUE TITLE
插件UI界面及使用操作BUG汇总(附优化建议)

### ISSUE THREAD

**Issue by Tourist-ChenHao** [Mr-Quin/danmaku-anywhere#17]
问题描述(操作BUG)：
1. 当选择要加载的弹幕后，点击MOUNT按钮进行挂载，程序没有任何提示或反馈来告知用户挂载状态。目前判断的标准在于界面能否有弹幕出现，或者打开网页调试查看DOM是否有正确渲染，即使程序错误也没有任何提醒。而页面最左侧的ICO按钮没有起到任何作用，这是最大设计错误
2. Chrome插件的菜单：Config / Option -> Edit Permissions; 居然没有滚动条，overflow=hidden，无法点击溢出外的选项(DANMAKU / STYLE 处于正常状态)
3. 菜单中的DANMAKU / Config，只能添加选项而不能删除，这让我十分无奈，而数据存储在DB里，这意味着我需要去调试工具重置数据
4. 页面最左侧的ICO按钮没有任何作用，连COMMENTS都显示不出来(成功加载)，还十分占位置影响美观

---
优化建议：
1. 建议扩展程序权限修改为：读取和更改您在所有网站上的所有数据；一次授权而非每次添加授权，提高体验
2. 挖掘页面左侧按钮功能，将扩展界面功能同步移植，便于点击功能；同时检测鼠标操作，当停止移动10s后，按钮opacity属性值设置为30%，提高观影体验
3. 插件只能拉取[弹弹play](https://www.dandanplay.com/)的数据，希望增加用户自主上传弹幕选项，并在readme写清格式要求(本人正在考虑用Python写一个本地爬取各大官网弹幕程序)
4. 请修复`问题描述`以上BUG

**Comment by Tourist-ChenHao** [comment]
附上截图：
<img width="400" alt="iShot_2024-04-07_16 11 36" src="https://github.com/Mr-Quin/danmaku-anywhere/assets/26212364/de6d45f9-6b29-4d3a-943d-c816d45fe4aa">
<img width="400" alt="iShot_2024-04-07_16 14 20" src="https://github.com/Mr-Quin/danmaku-anywhere/assets/26212364/8de970d3-3dc1-4539-9ad9-9a39ebc382df">
<img width="400" alt="iShot_2024-04-07_16 15 56" src="https://github.com/Mr-Quin/danmaku-anywhere/assets/26212364/9e0ba79e-7423-44f7-a166-307f5d84a249">

**Comment by Mr-Quin** [comment]
关于bug:
1. v0.9.0加入了一些挂载失败时的反馈
2. v0.9.0中修复了
3. 删除是说这个右上角的删除按钮吗？
![image](https://github.com/Mr-Quin/danmaku-anywhere/assets/8700123/cd1713ea-57f8-4107-9538-449ab980ace4)
4.这个应该也在v0.9.0修复了

关于优化建议
1. 这个一开始是这样的(<v0.8.0)，但是这样要求的权限太高了，对上架商城不利，后续可能会考虑改回去。现在的话，如果使用导入功能一次性导入多个可以同时授权。
2. v0.9.0改为了自动隐藏，鼠标靠近时出现，后续应该会增加可以自定义位置的功能。同时扩展界面的部分功能也会移植过去。
3. 手动上传弹幕，以及自定义弹幕源都在计划中

**Comment by Mr-Quin** [comment]
给用户手动上传弹幕开了个新issue #19

**Comment by Tourist-ChenHao** [comment]
哈哈哈，没想到在我提issues之前，我没有注意到，版本已经更新到v0.9.0.
新版的界面相比旧版，布局更加合理，已经解决我提出的 `问题描述` 的大部分问题，Config菜单中新增 上传/导出 配置功能，我觉得非常棒！！
但还是有点遗憾，DAMAKU菜单中已加载的弹幕没有像Config 那样的删除功能，还有希望作者能考虑将扩展程序权限修改为：读取和更改您在所有网站上的所有数据(会更便携，同时Chrome浏览器中可以设置插件权限)，因为插件除了下载弹幕需要联网，其他功能并没有联网需求，用户并不担心信息外泄。

**Comment by Tourist-ChenHao** [comment]
**附浏览器设置插件权限位置 截图**
<img width="550" alt="iShot_2024-04-08_22 02 54" src="https://github.com/Mr-Quin/danmaku-anywhere/assets/26212364/442e2b6a-0a6d-40e6-8a25-c374fccc9a4f">

**Comment by Mr-Quin** [comment]
v0.9.2先做了一波ux改动
这个issue先关了
权限和其他功能性改动再开新issue
