### ISSUE TITLE
可不可以制作一个油猴版本

### ISSUE THREAD

**Issue by patialo** [Mr-Quin/danmaku-anywhere#2]
你好，请问可以做一个油猴版本的吗，现在chrome导入比较麻烦，而且手动导入的无法多端同步，油猴相对而言可能比较方便。
若无此计划，close即可，谢谢。

**Comment by Mr-Quin** [comment]
有一个专门为Plex适配的版本，猴油可以用
https://mr-quin.github.io/danmaku-anywhere/plex-danmaku.user.js

插件版的无法转换成猴油脚本，不过会发布在chrome商店应该可以解决一部分问题
