### ISSUE TITLE
Plex中自动获取的剧名不正确

### ISSUE THREAD

**Issue by violetfinancier** [Mr-Quin/danmaku-anywhere#20]
例如在观看已刮削的mygo时，搜索弹幕关键词即为“BanG Dream! It's MyGO!!!!! - 第1季 · 第6集”，只有手动把后面的“ - 第1季 · 第6集”删除后才能通过剧名搜索，再手动匹配对应集数

**Comment by Mr-Quin** [comment]
可能是界面语言的问题
修复前你可以先试试把plex界面切换成英文

**Comment by violetfinancier** [comment]
切换英文的确可用，英文状态下" - 第1季 · 第6集"直接变成S1E6

**Comment by Mr-Quin** [comment]
regex没写好，下版本修复

**Comment by Mr-Quin** [comment]
Fixed in v0.10.0
