### ISSUE TITLE
(建议)允许按季匹配集数

### ISSUE THREAD

**Issue by violetfinancier** [Mr-Quin/danmaku-anywhere#22]
有一些动漫在tmdb中的信息，集数是隔季连续的，比如我心里危险的东西、租借女友等，因此plex刮削时就会将我心危第二季第1集刮削为S02E13，从而danmaku-anywhere会加载S02E13的弹幕

希望增加一个功能，能让插件手动选择弹幕集数后记住S02E13应该加载S02E01的弹幕，后续集数以此类推

**Comment by Mr-Quin** [comment]
能不能再描述的详细一点
我试了一下我心危，好像没有把第2季第1集识别为S02E13?

**Comment by violetfinancier** [comment]
TMDB里我心危第二季第一集编号是接着第一季第12集之后编号的，相当于我心危是个单季的连续剧，S2E1就是EP13
![image](https://github.com/Mr-Quin/danmaku-anywhere/assets/97280997/a2ae0d51-90f7-4873-9af6-1a169d94bc92)

所以第二季在plex里刮削的时候是从13集开始编号的，因为plex用了TMDB的剧集信息
![image](https://github.com/Mr-Quin/danmaku-anywhere/assets/97280997/6f7f9e40-082d-4a14-9712-db342ced1fb9)

我在看第二季第一集的时候，插件加载了S2E13；看第二季第二集的时候，插件搜索了S2E14
![image](https://github.com/Mr-Quin/danmaku-anywhere/assets/97280997/78bf2495-40b5-47d1-b07e-67e0de84c3cb)

**Comment by violetfinancier** [comment]
我本地plex库也没有正确命名，所以没刮削出单集信息。刚才把文件从"S02E01"这种的都改成"S1E13"这样的后，剧集信息更新出来了，不过danmaku也只能手动匹配了，这个就关闭了

**Comment by Mr-Quin** [comment]
原来如此
单集映射目前感觉意义不大，但是接下来会加入一个”下一集“按钮，自动切换至下一集的弹幕，可能会方便一点。
