### ISSUE TITLE
（建议）允许本地按（多个）关键字屏蔽弹幕

### ISSUE THREAD

**Issue by violetfinancier** [Mr-Quin/danmaku-anywhere#23]
弹幕中总有比较老或者不喜欢的梗（比如胖虎），希望可以屏蔽

**Comment by Mr-Quin** [comment]
v0.10.2
在弹幕设置页面里加了一页
支持regex
![image](https://github.com/Mr-Quin/danmaku-anywhere/assets/8700123/47a51232-889e-49de-9e37-774cd9046400)
![image](https://github.com/Mr-Quin/danmaku-anywhere/assets/8700123/32bc2283-4298-4fc6-a358-813cea967b5c)
