### ISSUE TITLE
支持导入其他弹幕格式

### ISSUE THREAD

**Issue by wang713821** [Mr-Quin/danmaku-anywhere#26]
弹幕格式为json还是报错

![TNVO6QOK0` G1_ IT 7(J1J](https://github.com/user-attachments/assets/805d62f3-004b-4f8a-b56e-66d7d5ff8807)

**Comment by Mr-Quin** [comment]
能贴一下JSON内容吗，太长的话可以只保留1条弹幕
目前这个导入功能只能导入特定格式的弹幕（没写入文档），导出的弹幕是无法导入的。这个功能下版本加上。

**Comment by Mr-Quin** [comment]
这是从哪里获取的？格式有文档吗

**Comment by yuanxiandong** [comment]
[danmu.zxz.ee.json](https://github.com/user-attachments/files/16500360/danmu.zxz.ee.json)

**Comment by wang713821** [comment]
[dmku.wevip.cc.json](https://github.com/user-attachments/files/16500377/dmku.wevip.cc.json)

**Comment by Mike-Hash-Steven** [comment]
下次能支持.xml或ass格式的弹幕吗

**Comment by Mike-Hash-Steven** [comment]
请问如何将xml文件转化为可导入的格式

**Comment by Mr-Quin** [comment]
@Mike-Hash-Steven 
> 请问如何将xml文件转化为可导入的格式

xml可以转换成json，比如https://www.bejson.com/xml2json/
再从json转换成可导入的格式，可导入的格式写在说明里了


> 下次能支持.xml或ass格式的弹幕吗

xml可以转换成json，ass弹幕一般也可以转换成json
暂不考虑支持json以外的格式，但是会考虑支持不同的json格式

可以在这里发一下你的弹幕文件（json）

**Comment by Mike-Hash-Steven** [comment]
[隐秘的角落1.json](https://github.com/user-attachments/files/16519556/1.json)
请问大佬我这个为啥不可以

**Comment by Mr-Quin** [comment]
格式不对
这个应该可以了
[隐秘的角落1.json](https://github.com/user-attachments/files/16519753/1.json)

和各种弹幕格式的对接之后版本添加

**Comment by Mike-Hash-Steven** [comment]
> 格式不对 这个应该可以了 [隐秘的角落1.json](https://github.com/user-attachments/files/16519753/1.json)
> 
> 和各种弹幕格式的对接之后版本添加

哇塞，这个真的可以了，请问怎么样才能够修改成这样的格式？

**Comment by tengfeij** [comment]
能不能增加几个弹幕源，比如B站腾讯视频之类的

**Comment by Mr-Quin** [comment]
> 能不能增加几个弹幕源，比如B站腾讯视频之类的

有稳定的开放API的话可以做对接

**Comment by tengfeij** [comment]
大佬要不看看这个项目：https://github.com/cxfksword/jellyfin-plugin-danmu

**Comment by Mr-Quin** [comment]
这个属于后端插件，运行在服务器上的，可以爬取各种弹幕源。我这个是前端，做不了这种。只能对接API，或者用户上传弹幕

**Comment by Mr-Quin** [comment]
我先做一个转换器，允许导入其他弹幕源的文件。
对接其他弹幕源（搜索，爬取等）还要再琢磨

**Comment by Mr-Quin** [comment]
v0.12.1中增加导入其他来源（b站，爱奇艺等）弹幕的功能，支持xml导入

需要支持其他什么格式的可以在这里反馈

**Comment by Mr-Quin** [comment]
> 这个属于后端插件，运行在服务器上的，可以爬取各种弹幕源。我这个是前端，做不了这种。只能对接API，或者用户上传弹幕

测试了一下发现service worker是可以和这些网站的API交互的，所以应该是可以实现搜索，爬取弹幕的功能，但是由于要添加这些功能要重写一堆东西，所以以后再说。

**Comment by Mr-Quin** [comment]
v0.13.0
新增实验性质的B站弹幕源
