### ISSUE TITLE
[FEAT]关于b站弹幕源的上限3600，是b站那边限制吗？还是作者出于某种考虑？

### ISSUE THREAD

**Issue by xxhh0001** [Mr-Quin/danmaku-anywhere#29]
**功能说明**
希望如果可能的话可以提升弹幕上限，或者改为自定义？

**使用场景**
如果是电影的话，时长较长，3600的弹幕可能相对较少，会导致画面较空

**Comment by Mr-Quin** [comment]
现在使用的方式获取弹幕上限根据视频长度有3600、9600等，是b站设置的
0.13.1新增加了一种上限更高的方式，但是速度更慢。设置中更改
