### ISSUE TITLE
怎么在alist中使用？

### ISSUE THREAD

**Issue by 779943132** [Mr-Quin/danmaku-anywhere#32]
在自己搭建的alist中播放视频，插件好像识别不到在播放的视频，这个是没适配还是我设置有问题
视频元素：video
连接格式：http://10.0.0.2/*

**Comment by 779943132** [comment]
已经设置好了XD需要加上端口号

**Comment by Mr-Quin** [comment]
我写进文档里

**Comment by 779943132** [comment]
> 我写进文档里

麻烦大佬了，要是能对alist适配一下自动识别弹幕就更好了🙏

**Comment by Mr-Quin** [comment]
> > 我写进文档里
> 
> 麻烦大佬了，要是能对alist适配一下自动识别弹幕就更好了🙏

这个再开一个issue吧，有空了研究一下
