### ISSUE TITLE
[BUG]alit找不到视频元素

### ISSUE THREAD

**Issue by 779943132** [Mr-Quin/danmaku-anywhere#34]
**Bug 描述**
![image](https://github.com/user-attachments/assets/14bffd4c-b8b5-4ce1-9cc3-45111731b5f9)
alist配置后播放视频去装载弹幕提示找不到视频元素
![image](https://github.com/user-attachments/assets/042ba1c1-5945-46a8-82cd-d4ef2bd6064b)
修改视频元素后可以找到视频元素
![image](https://github.com/user-attachments/assets/97f2d7f4-6b55-43d9-bd70-823bfd72e412)
然后要是再出去播放另一个视频还是会提示找不到视频元素
![recording](https://github.com/user-attachments/assets/b1b3ce8a-3da4-448f-94a8-94bcb02925eb)
具体复现可以看一下上面gif

**Comment by Mr-Quin** [comment]
以复现并修复
商店应该过几个小时就更新了
