### ISSUE TITLE
优化对iframe播放器的适配

### ISSUE THREAD

**Issue by truewhile** [Mr-Quin/danmaku-anywhere#39]
**Bug 描述**
请说明bug内容以及复现方法
https://dick.xfani.com/
这个视频网站，里面视频元素是video，但是设置后装载弹幕显示未找到视频元素
![image](https://github.com/user-attachments/assets/3b2f57a5-539e-4130-b2d8-14e5d3a853e3)
![image](https://github.com/user-attachments/assets/83ddcaa2-34d3-4651-bed8-e34cf348e72f)
![image](https://github.com/user-attachments/assets/bd959cb0-b80f-43fe-846b-cce925566fa8)
视频元素是不是也换成xPath比较好

**Comment by Mr-Quin** [comment]
这个网站用的iframe播放器，所以url这里要填iframe的地址
https://*.moedot.net/*
之后想办法优化一下iframe的体验

**Comment by 779943132** [comment]
换完之后可以了

**Comment by Mr-Quin** [comment]
这个issue开着记录一下iframe的问题
其实蛮多的

**Comment by Johy-Smith** [comment]
https://www.omofunz.com/
这个网站的视频信息在iframe标签中，但是填入iframe中的地址不能装填弹幕
![f12](https://github.com/user-attachments/assets/6d085e0a-eb08-4cc9-b62f-8d55be5feb74)
![编辑](https://github.com/user-attachments/assets/ffea7917-b870-44ca-b8ee-55f59f979af8)
![弹幕](https://github.com/user-attachments/assets/1cc18d08-4137-423e-8f87-63764c557888)

**Comment by Mr-Quin** [comment]
> https://www.omofunz.com/ 这个网站的视频信息在iframe标签中，但是填入iframe中的地址不能装填弹幕
这网站好像屏蔽境外ip，我再想想办法
这个最好再开一个issue @Johy-Smith

**Comment by Johy-Smith** [comment]
> > https://www.omofunz.com/ 这个网站的视频信息在iframe标签中，但是填入iframe中的地址不能装填弹幕
> 
> 这网站好像屏蔽境外ip，我再想想办法 这个最好再开一个issue @Johy-Smith

好的 那我再开一个issue  这个网站打开F12会被监测 不允许直接打开

**Comment by Mr-Quin** [comment]
v0.16.0
