### ISSUE TITLE
突然无法进行搜索，提示截图如下

### ISSUE THREAD

**Issue by violetfinancier** [Mr-Quin/danmaku-anywhere#40]
**Bug 描述**
尝试过完全关闭浏览器后重启，也尝试过卸载扩展后于商店重新安装，也尝试过备份并删除搜索配置后重新添加，目前仍未解决。不知是否与网络环境或网络工具有关？
![image](https://github.com/user-attachments/assets/5ff2bc29-0245-4254-8657-148dc083f152)

**相关日志**
如果有的话，请提供错误报告或日志

**Comment by Mr-Quin** [comment]
可能跟网络有关吧，我还没碰到过这个问题

可以提供一下日志和请求，操作如下

https://github.com/user-attachments/assets/41717abd-0b80-4e02-8990-fa422de8c376

**Comment by violetfinancier** [comment]
[jnflbkkmffognjjhibkjnomjedogmdpo-1727752444321.log](https://github.com/user-attachments/files/17198864/jnflbkkmffognjjhibkjnomjedogmdpo-1727752444321.log)
[jnflbkkmffognjjhibkjnomjedogmdpo.zip](https://github.com/user-attachments/files/17198875/jnflbkkmffognjjhibkjnomjedogmdpo.zip)

**Comment by Mr-Quin** [comment]
看日志是403了，直接访问api试试？
[https://api.dandanplay.net/api/v2/search/episodes?anime=%E8%B4%A5%E7%8A%AC&episode=
](https://api.dandanplay.net/api/v2/search/episodes?anime=%E8%B4%A5%E7%8A%AC&episode=
)
推测是弹弹Play API方面的限制

**Comment by violetfinancier** [comment]
[jnflbkkmffognjjhibkjnomjedogmdpo-1727752444321.log](https://github.com/user-attachments/files/17198899/jnflbkkmffognjjhibkjnomjedogmdpo-1727752444321.log)
是403，所以要关闭网络工具使用吗？

**Comment by violetfinancier** [comment]
可以了，添加了直连，感谢帮助~
