### ISSUE TITLE
大佬，请问nyacg这个网站要怎么添加

### ISSUE THREAD

**Issue by yangchris4** [Mr-Quin/danmaku-anywhere#41]
一直用这个看番剧  这个网站   https://www.nyacg.net/ 
我在控制台那边 document.querySelectorAll('video')
没显示出来视频元素，出来奇怪的东西
请问这个网站需要怎么添加呢，谢谢大佬
![WeChat截图_20241002115131](https://github.com/user-attachments/assets/cc759ef5-2a79-47fb-b21e-f39018d9973c)

**Comment by Mr-Quin** [comment]
模式填
```
https://play.nyacg.net/*
```
![image](https://github.com/user-attachments/assets/0eda7251-fc71-4f9d-8f68-8cebf8e8280f)
