### ISSUE TITLE
请问弹幕卡顿可能是什么问题

### ISSUE THREAD

**Issue by Desmond9527** [Mr-Quin/danmaku-anywhere#43]
**Bug 描述**
弹幕成功挂载后大概每1秒会顿一下，然后继续滚动弹幕，
将每秒最大弹幕数量改成1还是卡顿，此时弹幕数量已经很少了
系统macos 10.15，浏览器edge 128.0.2739.63
网页是https://nkvlog.com/play/3-1-493.html
装填url是https://op.xn--it-if7c19g5s4bps5c.com/player/*
**相关日志**
如果有的话，请提供错误报告或日志

**Comment by Mr-Quin** [comment]
这个网站我打不开
是只有这个网页卡吗？
能不能录个视频，包含网页日志

**Comment by Desmond9527** [comment]
https://nkvlog.com/play/3-1-493.html
这个网页打不开可以尝试关代理试一下，网站可能屏蔽了外网ip

或者打开这个网站
视频页：https://wuwubiz.com/vodplay/487005-8-1.html#slide{1}
发布页：https://flmre.com/
这个网页也一样，弹幕每秒卡一下

采用类似模版的视频站好像都一样，其他站点我这边测试正常

**Comment by Desmond9527** [comment]
https://czzy.top/v_play/bXZfMTgyMTEtbm1fMQ==.html
这个网站也复现了一样的问题

**Comment by Mr-Quin** [comment]
> https://czzy.top/v_play/bXZfMTgyMTEtbm1fMQ==.html 这个网站也复现了一样的问题

这个网站我进得去
确实有这个问题，可以看到隔一段时间会卡一下
![image](https://github.com/user-attachments/assets/b8fc1c2c-1969-40dc-a350-0f21d17952c0)

但是这个卡来源与网站本身的一个脚本，不是拓展
这个脚本在做一些很神秘的事情，我看看有没有解决办法，估计希望不大

**Comment by Mr-Quin** [comment]
稍微研究了一下
这个卡顿是来自脚本的反调试功能，每两秒一次。而且这个脚本同时负责注入播放器，所以也不能直接屏蔽掉。不过这个网站上好像也不是每个视频都会卡，根据加载的播放器而异。
总之这个卡顿不是拓展导致的所以我也没有什么好办法
