### ISSUE TITLE
希望增加开启关闭弹幕的快捷键

### ISSUE THREAD

**Issue by Desmond9527** [Mr-Quin/danmaku-anywhere#44]
**功能说明**
希望增加快捷键可以一键开启关闭弹幕

**使用场景**
有时视频里面一些内容被弹幕遮挡，需要临时关闭一下弹幕，然后马上重新打开，目前只能点击加号，选择卸载弹幕，非全屏模式下可以这样操作，全屏模式点击加号无反应，必须先退出全屏才能开关弹幕，建议增加快捷键，方便操作

**其他内容**
其他可供参考的内容，如：
- 截图
- 其他有类似功能的项目

**Comment by Mr-Quin** [comment]
可以

**Comment by Mr-Quin** [comment]
v0.15.2中加入
