### ISSUE TITLE
age动漫播放器识别异常

### ISSUE THREAD

**Issue by operatorLyu** [Mr-Quin/danmaku-anywhere#45]
**Bug 描述**
在age动漫页面一直显示video node is not ready
![image](https://github.com/user-attachments/assets/ccbaf051-2e98-4142-a44e-8b3a5d72aa43)
![image](https://github.com/user-attachments/assets/bd9e3173-5c3d-4b2b-9df2-c9107dfaf9dc)

**Comment by Mr-Quin** [comment]
这个网站的视频在iframe里，模式填iframe的地址
`https://43.240.156.118:8443/*`
