### ISSUE TITLE
请问大佬是否可以增加更长的弹幕进度调整的功能

### ISSUE THREAD

**Issue by nllnlnln** [Mr-Quin/danmaku-anywhere#46]
**功能说明**
类似于平时本地看视频时，调整音轨或者字幕，使其前进多少分钟或者后退多少分钟以适应当前实际进度
看到了扩展里面有“时间轴”调整，里面最多只能调整5s再长就调整不了了。
（可以了可以了，原来还可以自己设置，hhh，抱歉抱歉）

**使用场景**
有些网站的视频和官方视频有差别。官方给视频加了几分钟的片头片尾，导致弹幕进度相差比较大。
还有一些是在B站上传的电影，然后把一个电影分成了多P，每个分P内加了一些无用片段（他们说是更好地防封），当我加载这样的弹幕给到第三方影视网站的电影时，弹幕和影片实际进度也相差较大。

**其他内容**
我不知道我的描述是否清晰，如果还有描述不清楚的地方， 请您指出

**Comment by nllnlnln** [comment]
抱歉抱歉，我找到了怎么调整弹幕进度了，而且，那个调整时间长短不只5s，可以自己设定。
这个issue我自己还删不掉，只能麻烦大佬到时候删一下😭。

**Comment by Mr-Quin** [comment]
你一说我想起来了
0.15.3把弹幕设置添加至弹出界面
