### ISSUE TITLE
优化时间轴调整

### ISSUE THREAD

**Issue by davidzwb** [Mr-Quin/danmaku-anywhere#47]
**功能说明**
希望能增大时间轴的调整范围

**使用场景**
现在 danmaku-anywhere (v0.15.3) 只能在正负 5000ms 即 5 秒的范围内调整时间轴，但是很多电视剧资源是删除了开头的片头曲和广告的，导致弹幕的时间轴甚至会偏移几十秒到几分钟。

**Comment by Mr-Quin** [comment]
时间是可以手动输入的
滑块的时间区间太长的话不好精确控制
如果有好建议欢迎提出

**Comment by davidzwb** [comment]
主要是之前手动输入遇到了问题，我是下载视频放到 jellyfin 中，然后用 jellyfin 的网页播放器搭配 danmaku-anywhere 来看动漫或电视剧弹幕的，结果 jellyfin 的网页播放器对数字键有快捷键映射，导致在视频左下角的 danmaku-anywhere 按钮设置时间轴的时候，一按数字键就跳转视频，始终无法在输入框中输入数字，最后发现可以其他地方输入数字后粘贴过来。

**Comment by Mr-Quin** [comment]
这算个bug
或者插件本体中也可以输入
