### ISSUE TITLE
填入iframe中的地址无法装填弹幕

### ISSUE THREAD

**Issue by Johy-Smith** [Mr-Quin/danmaku-anywhere#48]
**Bug 描述**
请说明bug内容以及复现方法

https://www.omofunz.com/
这个网站的视频信息在iframe标签中 但是填写iframe标签中的地址也不能装填弹幕

**相关日志**
如果有的话，请提供错误报告或日志

![f12](https://github.com/user-attachments/assets/952106c7-6c42-416f-a37d-ec2d764c6198)
![编辑](https://github.com/user-attachments/assets/37a8de1b-49ab-478e-81cb-246bcdc5ebcb)
![弹幕](https://github.com/user-attachments/assets/570017fa-da95-481d-8870-ea8f19f34587)

这个网站直接打开F12或者鼠标右键检查 会被监测

**Comment by Mr-Quin** [comment]
这个网站屏蔽我的ip，有点麻烦。
老哥可以提供一下网页和插件的日志，看看能不能看出什么

**Comment by Johy-Smith** [comment]
> 这个网站屏蔽我的ip，有点麻烦。 老哥可以提供一下网页和插件的日志，看看能不能看出什么

不知道怎么查看网页和插件的日志 我发下控制台、sources和Network的截图，以及sources、Network下面出现的文件吧

![网页F12](https://github.com/user-attachments/assets/e85f4368-56ce-47d2-a7bb-f02948ac218c)
![控制台](https://github.com/user-attachments/assets/710e72a8-0a0e-47e9-aac7-393270e3a1e0)
![sources](https://github.com/user-attachments/assets/f85695a6-ce28-4553-96fc-4c1373a16177)
![Network](https://github.com/user-attachments/assets/5b8ebacf-001f-4cdd-9026-f41914b7d58e)
[sources下面出现的文件.zip](https://github.com/user-attachments/files/17870330/sources.zip)
[Network下面出现的文件.zip](https://github.com/user-attachments/files/17870332/Network.zip)


另外 复制iframe标签中的地址 在新窗口中粘贴可以播放视频 新窗口打开f12后的视频地址又不一样了 如下所示

![新窗口的视频](https://github.com/user-attachments/assets/8316910a-c57f-405d-bc4d-9b4d143ac449)
![新窗口F12](https://github.com/user-attachments/assets/5814c72d-e829-45ab-a822-fc3dce1178e4)
![新窗口sources](https://github.com/user-attachments/assets/d005c063-aab7-46b2-8533-09dc9f20350b)
[新窗口source下的文件.zip](https://github.com/user-attachments/files/17870597/source.zip)

新窗口打开F12的视频地址再另外开个窗口粘贴访问 也能正常播放 然后再通过这个另外开的窗口 找到了视频统计信息中详细的视频地址（这句话不知道有没有用也先发下吧）

![新窗口F12](https://github.com/user-attachments/assets/a676af6a-0b33-4cb8-a3fc-5aeb642bb861)
![另外窗口](https://github.com/user-attachments/assets/dc3b3aac-9862-4ac3-b2f7-b6115d98f33b)
![另外窗口F12](https://github.com/user-attachments/assets/d364f3da-30c8-4ad1-b266-c5c6017375e4)
![视频最终地址](https://github.com/user-attachments/assets/5f090d0b-c91e-42c6-a604-bcdd3473386f)

原omofunz.com视频中 右键打开统计信息出现的视频地址是这个：

http://v16m-default.akamaized.net/cdfc0c1b202f58b9e4b30574b377e039/6740daa0/video/tos/alisg/tos-alisg-ve-0051c001-sg/ossgXF3DEESIgIoibhfDhP3ANMfwmDQ7BULnBR/?a=2011&amp;bti=MzhALjBg&amp;ch=0&amp;cr=0&amp;dr=0&amp;net=5&amp;cd=0|0|0|0&amp;br=3002&amp;bt=1501&amp;cs=0&amp;ds=4&amp;ft=XE5bCqT0mmjPD12j4L8J3wU7C1JcMeF~O5&amp;mime_type=video_mp4&amp;qs=0&amp;rc=ZztkNGY4O2ZkNDM1OjNnZkBpanFoeWo5cnd1dDMzODYzNEAtXmEzXzE1NTMxNS01NWNjYSNkMXNhMmRzLmRgLS1kMC1zcw==&amp;vvpl=1&amp;l=202411221300408579B6E5554A882C7CF0&amp;btag=e000a8000

原omofunz.com的iframe标签中的地址如下：
https://jx.cilicili.one/player/?url=dm295-8718-1-1
粘贴这个视频地址到新窗口中获取到的另外的视频地址如下：
https://jx.cilicili.one/player/analysis.php?v=dm295-8718-1-1
粘贴这个视频地址再开个窗口 得到的视频地址就是 原omofunz.com统计信息的视频地址了 如前面所示

我是个小白 插件方面只能看到这 其他就不知道了 大佬要是需要其他的信息我可以继续提供 但是需要告诉我怎么去找到（例如日志我不知道在哪........）

**Comment by Mr-Quin** [comment]
感谢提供信息

在这个网页中
https://jx.cilicili.one/player/analysis.php?v=dm295-8718-1-1
使用插件也提示同样的错误吗？

**Comment by Johy-Smith** [comment]
> 感谢提供信息
> 
> 能看到悬浮按钮说明脚本是正常注入的。可以看到这个网站有套娃的iframe，猜测可能是这中间有什么问题
> 
> 可以尝试两个操作： 在这个网页中 https://jx.cilicili.one/player/analysis.php?v=dm295-8718-1-1 尝试装填弹幕，看看能不能成功
> 
> 在https://www.omofunz.com/ 正常播放的情况下 尝试用插件本体的弹出窗口装填弹幕 ![image](https://private-user-images.githubusercontent.com/8700123/389151732-6924193d-bd7f-46a1-a609-266ac03974cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzMjc1NzQsIm5iZiI6MTczMjMyNzI3NCwicGF0aCI6Ii84NzAwMTIzLzM4OTE1MTczMi02OTI0MTkzZC1iZDdmLTQ2YTEtYTYwOS0yNjZhYzAzOTc0Y2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjNUMDIwMTE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzViY2U5MTZhMmQ2ZmY3MTkyODBhNWM3YWI0MTY2M2VkNDQzMDEyM2RjZjU4NGE5MWU3MWZmNGU5MzM2NjdjMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.JlS7qy3eKITRf5u9fXRM9dogo1hgRlU52QXrtUNt3Pc)

**Comment by Johy-Smith** [comment]
在这个网页中 https://jx.cilicili.one/player/analysis.php?v=dm295-8718-1-1 尝试装填弹幕    成功！能正常装填和卸载弹幕
在https://www.omofunz.com/ 正常播放的情况下 尝试用插件本体的弹出窗口装填弹幕   可以装填弹幕 但是有点小问题 
使用本体装填弹幕 能装填上去 但是会提示装填弹幕失败 如下图所示：

![弹幕bug](https://github.com/user-attachments/assets/6c66b0a0-0a9d-4a8a-a586-8abbacaf9817)

使用本体装填弹幕后 无法卸载弹幕 卸载弹幕按钮是禁用状态
使用本体装填弹幕后 再使用内置按钮卸载弹幕  此时卸载弹幕按钮是可选状态 点击卸载按钮后提示 弹幕已卸载 但是弹幕实际在视频中还会显示 没有任何改变 此时点击本体插件 装填弹幕和卸载弹幕按钮都是禁用状态

![内置按钮](https://github.com/user-attachments/assets/13309099-b2f6-4491-92ea-d95b35dbcb87)
![卸载](https://github.com/user-attachments/assets/321ec53f-2622-4219-a48f-78c911894cad)
![卸载弹幕失败](https://github.com/user-attachments/assets/87850840-e21c-4a92-bea9-fc6d6ed157b4)

**Comment by Mr-Quin** [comment]
试试把模式里的 `https://jx.cilicili.one/*`换成
`https://jx.cilicili.one/player/analysis.php*`

**Comment by Johy-Smith** [comment]
> 试试把模式里的 `https://jx.cilicili.one/*`换成 `https://jx.cilicili.one/player/analysis.php*`
> 
> 猜测是这个原因 这个网站有两个iframe都是`https://jx.cilicili.one/*`开头的，所以注入了两次脚本，看到的悬浮按钮其实是有两个叠在了一起。你点击的悬浮按钮是属于外层iframe的，但是视频是属于内层iframe的。使用插件本体会同时对所以脚本发送命令，其中一个成功，一个失败，所以虽然成功了但还是有错误信息。 把模式细化，只匹配内层的应该就可以了


使用这个方法成功解决这个问题了 但是现在又有新的bug
使用关键词搜索出来两个内容一致但是名字有点差异的番剧

![关键词搜索](https://github.com/user-attachments/assets/2928346c-76ba-47e4-804d-547c3de3c7f0)

名字是《不时轻声地以俄语遮羞的邻座艾莉同学》的番剧就是之前遇到问题时的视频 使用大佬给的方法成功解决问题
但是 名字是《不时用俄语小声说真心话的邻桌艾莉同学》的番剧 出现了不能使用插件装填弹幕 也没有内置按钮的问题
打开F12发现iframe标签中的地址不一样 此时iframe中的地址是：
https://play.cilicili.one/player/?url=jiandan-a34a42b608062126511087974fc5e42be2cd2bfb6a8625ebf73ce399396ca8b5444fadf590b8e778119bd911725ad2702b33156a1987cb1b02822ed753242f3aae4c57c14e7ea41ddcf6fc19bf31f4e205b14c2c8060dd7b2d6859323e676e53d57349c1d263f900d2eb677700d21ea5fe60743faf516858de0e56d3597fb19667449553136f6c09cd5c684f7c85992b

尝试在装填配置中使用  https://play.cilicili.one/*   出现了内置按钮 但是无法直接装填弹幕 只能使用本体插件装填弹幕
尝试在装填配置中使用 https://play.cilicili.one/player/*  还是不能使用内置按钮装填弹幕 只能使用本体插件装填弹幕
尝试在装填配置中使用 https://play.cilicili.one/player/?url* 也不行

![新问题的F12](https://github.com/user-attachments/assets/1c6c5905-4bb2-4638-871e-40ea3540cbf9)

**Comment by Mr-Quin** [comment]
他里面应该还藏了iframe
在另外一个标签页里打开
![image](https://github.com/user-attachments/assets/3d5ed838-3a0a-4620-9804-0731110b5d99)
看看里面还有什么

也可以试试 `https://*.cilicili.one/player/analysis.php*`

**Comment by Mr-Quin** [comment]
> https://play.cilicili.one/player/?url=jiandan-a34a42b608062126511087974fc5e42be2cd2bfb6a8625ebf73ce399396ca8b5444fadf590b8e778119bd911725ad2702b33156a1987cb1b02822ed753242f3aae4c57c14e7ea41ddcf6fc19bf31f4e205b14c2c8060dd7b2d6859323e676e53d57349c1d263f900d2eb677700d21ea5fe60743faf516858de0e56d3597fb19667449553136f6c09cd5c684f7c85992b

发现这个不屏蔽我的ip
里面确实还嵌了一个iframe
![image](https://github.com/user-attachments/assets/b142d210-ce0f-4e55-b0d3-6baf00b9eb56)
试了一下`https://*.cilicili.one/player/analysis.php*`是可以的

不过不排除https://www.omofunz.com/这个网站上有其他的，不符合这个模式的视频页。这种就只能单个视察，然后添加进配置中

**Comment by Johy-Smith** [comment]
> > https://play.cilicili.one/player/?url=jiandan-a34a42b608062126511087974fc5e42be2cd2bfb6a8625ebf73ce399396ca8b5444fadf590b8e778119bd911725ad2702b33156a1987cb1b02822ed753242f3aae4c57c14e7ea41ddcf6fc19bf31f4e205b14c2c8060dd7b2d6859323e676e53d57349c1d263f900d2eb677700d21ea5fe60743faf516858de0e56d3597fb19667449553136f6c09cd5c684f7c85992b
> 
> 发现这个不屏蔽我的ip 里面确实还嵌了一个iframe ![image](https://private-user-images.githubusercontent.com/8700123/389161774-b142d210-ce0f-4e55-b0d3-6baf00b9eb56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzMzM2MDksIm5iZiI6MTczMjMzMzMwOSwicGF0aCI6Ii84NzAwMTIzLzM4OTE2MTc3NC1iMTQyZDIxMC1jZTBmLTRlNTUtYjBkMy02YmFmMDBiOWViNTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjNUMDM0MTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTI3ZTAwMmFlZWQwZjFkOTBhYWUzOTQ3N2UxMjExN2U5MjlkNTZiODFkNGRkMGRkYmRiNWJlNDFlNDE4YTMyMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Nf9W4Zo1pGGLPSkLXF4CtATxJsGipvAP_go6rUqPXmU) 试了一下`https://*.cilicili.one/player/analysis.php*`是可以的
> 
> 不过不排除https://www.omofunz.com/ 这个网站上有其他的，不符合这个模式的视频页。这种就只能单个视察，然后添加进配置中

感谢大佬 这个确实可以 
遇到这种情况只能单独重新添加配置了吗？

**Comment by Mr-Quin** [comment]
目前来说就只能单独添加模式了，像这样可以添加多个
![image](https://github.com/user-attachments/assets/cfd15dcb-0797-4a69-bc74-e5eeb4e2640a)

正在想办法优化中 #39 的目标是不特殊对待iframe，也就是模式写https://www.omofunz.com/ 即可

**Comment by Johy-Smith** [comment]
现在又遇到个问题 
https://www.lmm36.com/网站中的视频是在video标签中的 但是填入video中的地址不能装填弹幕
填入iframe标签中的地址就可以装填大部分视频的弹幕
但是 https://www.lmm36.com/play/28_1_1.html 在这个番剧视频中 有两种线路资源 使用聚合线路播放视频可以正常装填和卸载弹幕 使用dp云播线路就只能使用插件装填弹幕了 并且卸载不了弹幕
打开F12发现 
使用聚合线路播放视频时 视频地址在video标签中 地址是
http://v16m-default.akamaized.net/7427944173e399bc6b0f2b3c057cf75d/6741ab62/video/tos/alisg/tos-alisg-v-0000/oAnK4BbcSQ9NGelGHSYCAJgeDeUD2I9AbYJBiX/?a=2012&amp;bti=MzhALjBg&amp;ch=0&amp;cr=0&amp;dr=0&amp;net=5&amp;cd=0%7C0%7C0%7C0&amp;br=1902&amp;bt=951&amp;cs=0&amp;ds=3&amp;ft=XE5bCqT0mmjPD12hly8J3wUF3aT_jeF~O5&amp;mime_type=video_mp4&amp;qs=0&amp;rc=Mzw8ODRkPGQ3ZmdnZGU7OkBpM3gzcWY6ZjVnZzMzODYzNEBiNDFeYGJgXzAxYV8tXzBiYSNzbGkvcjRfYnBgLS1kMC1zcw%3D%3D&amp;vvpl=1&amp;l=20241123035221735A0D639422E12D6CC3&amp;btag=e000a8000

用iframe标签中的地址可以正常装填弹幕

使用dp云播线路播放视频时 视频地址在video标签中 地址是
http://videooc.tc.qq.com/1098_0efc1cf6a43ed7c001f91add508eb9d0.f0.mp4?ptype=http&amp;vkey=1CC096B81AE3BB97F6900ACBF7FF8C250291C9D185CCB71FE46365F69C7A4B3FC0AA6EEED6286A513E47B1321D263C0722306E9E627B7BDB&amp;sdtfrom=v6000&amp;owner=0&amp;chgtype=712&amp;vuin=1170097879

使用iframe标签中的地址只能通过插件装填弹幕 但是不能卸载弹幕 并且这个video视频地址无法访问

![dp云播F12](https://github.com/user-attachments/assets/ea4332ee-66c0-4599-ae8c-5bbd0d22a564)
![微信截图_20241123121551](https://github.com/user-attachments/assets/31e0f3a7-91f1-49a6-8455-ab23b4189d49)

**Comment by Mr-Quin** [comment]
这个网站我进的去

也是同样的套娃iframe问题
![image](https://github.com/user-attachments/assets/c401b1bf-ea88-4a0d-8533-cd2ca3435b8c)

模式应该使用最接近video的iframe的地址。图中为iframe 2，然后还要避免选择iframe 1

可以用这个`https://yun.366day.site/yunbox/*`，我测试两个线路都可以正常使用

**Comment by Johy-Smith** [comment]
> 这个网站我进的去
> 
> 也是同样的套娃iframe问题 ![image](https://private-user-images.githubusercontent.com/8700123/389171254-c401b1bf-ea88-4a0d-8533-cd2ca3435b8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNDEyNTQsIm5iZiI6MTczMjM0MDk1NCwicGF0aCI6Ii84NzAwMTIzLzM4OTE3MTI1NC1jNDAxYjFiZi1lYTg4LTRhMGQtODUzMy1jZDJjYTM0MzViOGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjNUMDU0OTE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGY1YmU0MzYxYWI5ZWM4Mjg1YmE2NjA1ZmI2YjZlODEwMTQ0ZjgxYTI5Mjg2NjA0NjI3NzBjYTA2NzUzN2JjZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.qxy1uXQ2ZDbege-avCtbnXN1XNeoBJrfppoc1-sQ5JU)
> 
> 模式应该使用最接近video的iframe的地址。图中为iframe 2，然后还要避免选择iframe 1
> 
> 可以用这个`https://yun.366day.site/yunbox/*`，我测试两个线路都可以正常使用

我刚测试不能装填弹幕啊 使用https://yun.366day.site/yunbox/*  连按钮都没了 使用插件装填弹幕也装填不上
使用 https://yun.366day.site/*  除了这个番剧的dp云播线路不能通过按钮装填弹幕 用插件是可以装填弹幕的
番剧链接：https://www.lmm36.com/play/28_1_1.html  

![弹幕按钮装填失败](https://github.com/user-attachments/assets/101bf4c6-0f29-4358-aa14-5fdaa694c33c)
![无按钮](https://github.com/user-attachments/assets/9bd30086-6a35-4a0b-9d60-837864d0b9cd)
![弹幕按钮装填失败](https://github.com/user-attachments/assets/c6041fa1-8176-4d57-8641-4b68a91cc95c)
![装填成功](https://github.com/user-attachments/assets/553fddb2-1422-4a06-97fb-20a1a4808d2f)

**Comment by Mr-Quin** [comment]
还是猜测，可能不同地区有不同的iframe地址

> ![image](https://github.com/user-attachments/assets/6874869b-b30e-4fc1-a426-ac54e21ebaa8)

这张截图里往上翻一点点，看看iframe地址
我刚才测试的时候两个线路都是`https://yun.366day.site/yunbox/`开头的地址
如果一个线路能用，一个不能，应该说明地址不同

**Comment by Johy-Smith** [comment]
云播：
![云播](https://github.com/user-attachments/assets/e88611c4-7563-4a94-82ed-a471cc5a601c)

聚合：
![聚合](https://github.com/user-attachments/assets/dbcc4ccd-b536-40b5-b420-a37c273f1e69)

**Comment by Mr-Quin** [comment]
看上去地址是一样的
我又试了试，发现配置顺序这里有bug

![image](https://github.com/user-attachments/assets/a7aab1ff-d68e-4ccd-834c-71a63c0e9f5d)
在这里，把“路漫漫”的模式替换成`https://yun.366day.site/yunbox/*`，“测试”先暂时删除试试

**Comment by Johy-Smith** [comment]
> 看上去地址是一样的 我又试了试，发现配置顺序这里有bug
> 
> ![image](https://private-user-images.githubusercontent.com/8700123/389181453-a7aab1ff-d68e-4ccd-834c-71a63c0e9f5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNDc4NDAsIm5iZiI6MTczMjM0NzU0MCwicGF0aCI6Ii84NzAwMTIzLzM4OTE4MTQ1My1hN2FhYjFmZi1kNjhlLTRjY2QtODM0Yy03MWE2M2MwZTlmNWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjNUMDczOTAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2I0YzY2YjBhMTUyMzU0OTA5ZWUwZWZkM2QwMmQzYWZiYzE2MGY4MTUzYmI5NDk2ODMwNTU1M2Q5MGEwMDU2MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Aw33cLM-PAGttqjIadpUcTV1TuE-dxtXXWkaENN7-nE) 在这里，把“路漫漫”的模式替换成`https://yun.366day.site/yunbox/*`，“测试”先暂时删除试试

按照这个方法成功装填弹幕了 但是为什么呢？我之前没有启用过前面的配置 只启用https://yun.366day.site/yunbox/*的配置却不行
删除https://yun.366day.site/*的配置后 用https://yun.366day.site/yunbox/*的配置就可以


另外在这个网站下测试其他的番剧 发现这个地址的dp云播使用的视频地址又不一样了：https://www.lmm36.com/play/6429_2_1.html

![鬼灭之刃F12](https://github.com/user-attachments/assets/acb6350e-3619-43cd-a06f-43599f6a4f96)

这个地址的番剧 使用dp云播线路播放 要是使用https://yun.366day.site/yunbox/*的配置就会出现没有按钮 插件装填弹幕也装填不了的bug

我把https://yun.366day.site/yunbox/*和https://yun.366day.site/* 添加到同一个配置中可以解决这个问题
![微信截图_20241123155846](https://github.com/user-attachments/assets/58a0ffb2-ed65-4b12-8e62-824b51fd1cba)

所以在https://www.lmm36.com/ 这个网站中看番剧 就要这样配置两个模式吗 大佬有没有什么优化成一条配置的方法呀

**Comment by Johy-Smith** [comment]
不行 这样配置不行  在配置中添加两种模式的话 能解决https://www.lmm36.com/play/6429_2_1.html 这个地址的dp云播线路问题
但是 前面的番剧https://www.lmm36.com/play/28_1_1.html的dp云播线路又变成原来那样只能通过插件本体装填弹幕了

这个配置中如果只使用https://yun.366day.site/yunbox/*可以解决第一个视频dp云播线路的问题 但是第二个视频的dp云播线路不能通过按钮装填弹幕

如果只使用https://yun.366day.site/*模式可以解决第二个视频云播线路的问题 但是第一个视频的云播线路又不能通过按钮装填弹幕了

![弹幕装填失败](https://github.com/user-attachments/assets/4dc5158c-67dc-44c4-9bad-c0749fdb55b0)

**Comment by Mr-Quin** [comment]
> 但是为什么呢

简单来说就是有个bug，由于配置是从上往下匹配的，在模式有重合的情况下会导致上面的配置覆盖下面的配置
这里**路漫漫**在**测试**上面，而且**路漫漫**的模式`https://yun.366day.site/*`是**测试**的模式`https://yun.366day.site/yunbox/*`的超集。这个bug就导致实际匹配到的配置是**路漫漫**，不是**测试**。而**路漫漫**是禁用的，就没有悬浮按钮了。
![image](https://github.com/user-attachments/assets/7d295218-f51c-4a69-8c06-e884dcf3940d)


> 但是第二个视频的dp云播线路不能通过按钮装填弹幕

对的
![image](https://github.com/user-attachments/assets/1965df8b-8b11-46a0-a159-68bff54d61c6)
这个配置相当于只写了一条`https://yun.366day.site/*`，因为`https://yun.366day.site/*`完全包含`https://yun.366day.site/yunbox/*`
所以就回到之前的问题了

这个问题暂时没有好的解决办法，要等 #39 了。

**Comment by Johy-Smith** [comment]
好的 感谢大佬解决这些问题 大佬辛苦了  期待以后能更好的优化插件
