### ISSUE TITLE
导出的弹幕再导入失败

### ISSUE THREAD

**Issue by CYM-YYds** [Mr-Quin/danmaku-anywhere#50]
![image](https://github.com/user-attachments/assets/5c528ef5-72bf-47e9-84ea-5ca39e6092ac)
![image](https://github.com/user-attachments/assets/74ab1fd3-0dda-493c-a05e-e10c094c1a1e)
无法导入之前导出的弹幕

**Comment by Mr-Quin** [comment]
能发一下json文件吗

**Comment by CYM-YYds** [comment]
[银魂 - 第20话 要小心传送带.json](https://github.com/user-attachments/files/18172825/-.20.json)

**Comment by CYM-YYds** [comment]
> 能发一下json文件吗
[银魂 - 第20话 要小心传送带.json](https://github.com/user-attachments/files/18172833/-.20.json)
